In [23]:
# Cities and their climate conditions to calculate the yield of apples

w1, w2, w3 = 0.3, 0.2, 0.5

kanto = [ 73, 67, 73] 
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

weights = [w1, w2, w3]

In [24]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
        return result
    

In [25]:
kanto

[73, 67, 73]

In [26]:
weights 

[0.3, 0.2, 0.5]

If i try to run two variables in a single cell it will only return me the output of the last variable

In [27]:
weights
kanto

[73, 67, 73]

In [28]:
crop_yield(kanto, weights)

21.9

In [29]:
crop_yield(johto, weights)

27.3

# We can directly use teminal command directly in the cell in order to install a specific liberary or anything else git commands by prefixing "!" before the command 

!pip install numpy 

In [30]:
!pip install numpy

In [2]:
import numpy as np

In [32]:
kanto = np.array([73, 67, 43])

In [33]:
kanto 

array([73, 67, 43])

In [34]:
weights = np.array([w1, w2, w3])

In [35]:
weights

array([0.3, 0.2, 0.5])

In [36]:
type(kanto)

numpy.ndarray

# Operating on Numpy arrays 

In [37]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

In [38]:
np.dot(kanto, weights)

np.float64(56.8)

In [39]:
(kanto * weights).sum()

np.float64(56.8)

## exploring sum() for more clarification 

In [40]:
g = np.array([1, 2, 3, 4, 5,])
h = np.array([9, 8, 6, 5, 4,])

(g + h).sum()

np.int64(47)

## Continuing with numpy

### now we have matrix in numpy which are also called 2 dimensional array in numpy we can take multiple dimensional array to store more data in a single variable we will do this for above cities right now

In [41]:
climate_data = np.array([   [73, 67, 43],
                            [91, 88, 64],
                            [87, 134, 58],
                            [102, 43, 37],
                            [69, 96, 70]])

# This can be written in a single line but to resemble a matrix we have written like this, you can take any dimension of array by just nesting list inside list and list.

In [42]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

we can even see the shape of the array by using attribute .shape which will give no of the elements in the parent list and no of children in meach parent 

In [43]:
climate_data.shape

(5, 3)

In [44]:
# here is one more example of 
weights.shape

(3,)

cose this list is one dimensional that's y you can't see the scond element in the output 

## lest take an example of 3D array

In [45]:
arr3 = np.array(
    [
        [
            [11, 12, 11],
            [12, 14, 14]
        ],
        [
            [16, 16, 17],
            [18, 10, 17]
        ]
    ]
)

In [46]:
arr3.shape

(2, 2, 3)

In [47]:
arr3 = np.array(
    [
        [
            [11, 12, 11],
            [12, 14, 14, 14] #Here you can se what is the error
        ],
        [
            [16, 16, 17],
            [18, 10, 17]
        ]
    ]
)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [48]:
weights.dtype

dtype('float64')

In [49]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [50]:
# we can also perform matrix multiplication by simply using "@" in between the matrix like we use mathematical operators
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

# Working with CSV files which stands for Comma Separated Values format

we will also be using urllib which is used to import urls in our document

In [ ]:
import urllib.request as url

url.urlretrieve(
    'http://hub.jovian.ml,wp-content/uploads/2020/08/climate.csv','cliate.txt'
)

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [ ]:
climate_data = np.genfromtxt('climate_simple.txt', delimiter=',', skip_header=1)

In [ ]:
climate_data

array([[ 16., 138.,  38.],
       [-10., 203.,  97.],
       [ 31., 147.,  22.],
       ...,
       [  3., 277.,  34.],
       [ 48.,  35.,  81.],
       [ 10., 163.,  19.]], shape=(10000, 3))

In [ ]:
climate_data.shape

(10000, 3)

In [ ]:
weights = np.array([0.3, 0.2, 0.5])
yields = climate_data @ weights
yields

array([51.4, 86.1, 49.7, ..., 73.3, 61.9, 45.1], shape=(10000,))

In [ ]:
yields.shape

(10000,)

we want to add this new data to the file climate_sample.txt as a new element in each row and a new column in the exesting matrix

In [ ]:
climate_result = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [ ]:
climate_result

array([[ 16. , 138. ,  38. ,  51.4],
       [-10. , 203. ,  97. ,  86.1],
       [ 31. , 147. ,  22. ,  49.7],
       ...,
       [  3. , 277. ,  34. ,  73.3],
       [ 48. ,  35. ,  81. ,  61.9],
       [ 10. , 163. ,  19. ,  45.1]], shape=(10000, 4))

In [51]:
np.savetxt('climate_result.txt',
            climate_result,
            fmt='%.2f',
            comments='',
            header='temperature,rainfall,humidity,yeild_apples'
)

NameError: name 'climate_result' is not defined

# Arithmetic operations and broadcasting 

In [ ]:
import numpy as np

A = np.array([
    [12, 45, 78, 23],
    [90, 11, 56, 34],
    [67, 89, 21, 43]
])

B = np.array([
    [25, 76, 99, 44],
    [34, 44, 55, 88],
    [12, 78, 43, 21]
])

In [ ]:
A + B

array([[ 37, 121, 177,  67],
       [124,  55, 111, 122],
       [ 79, 167,  64,  64]])

In [ ]:
A + 3

array([[15, 48, 81, 26],
       [93, 14, 59, 37],
       [70, 92, 24, 46]])

Numpy supports broadcasting in which array with two different dimensions but compatiable shapes can perform Arithmetic operations

In [ ]:
B.shape

(3, 4)

In [ ]:
C = np.array([4, 5, 6, 7])
C.shape

(4,)

In [ ]:
B + C

array([[ 29,  81, 105,  51],
       [ 38,  49,  61,  95],
       [ 16,  83,  49,  28]])

if you try to porint compersion between two arrays its possible but the answer will also be boolean 

In [ ]:
A == B

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
(A == B ).dtype

dtype('bool')

In [ ]:
A != B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A >= B

array([[False, False, False, False],
       [ True, False,  True, False],
       [ True,  True, False,  True]])

In [ ]:
(A >= B).sum()

np.int64(5)

The above argument is just adding True as 1 and Flase as 0

# Array indexing and slicing

In [ ]:
arr3 = np.array(
    [
        [
            [
                11,12,13,14
            ],
            [
                13,14,15,1
            ]
        ],
        [
            [
                15,16,17,21
            ],
            [
                63, 92, 36,18
            ]
        ],
        [
            [
                98,32,81,23
            ],
            [
            17,18,19.5,43
            ]
        ],        
    ]
)

In [ ]:
arr3.shape

(3, 2, 4)

now to access the element in this kind of array we have to provide multiple indexes, a note form the educatore just work form the outside

In [ ]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [ ]:
arr3[1,1]

array([63., 92., 36., 18.])

always remember the indexing starts with 0

In [ ]:
arr3[1,1,1]

np.float64(92.0)

In [ ]:
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. ,  1. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [ ]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [ ]:
arr3[1:,0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [ ]:
arr3[1:, :1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [ ]:
# now if i say i wanted to have elements last element of second matrix's second row and last element of third element's second row

arr3[1:, 1, 3] #By placing 1 in the middle the interpreter is selecting second row as default for both 2ed and 3ed array

array([18., 43.])

In [ ]:
# If you want to select specific elements for

### other ways to create numpy arrays 


In [52]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.random.rand(5)

array([0.01157008, 0.67771605, 0.25892022, 0.10526016, 0.14589292])

In [57]:
np.random.randn(2,3)

array([[-2.17920051, -0.55532361, -1.01141348],
       [ 0.43816272,  0.15790623,  0.07890416]])

In [58]:
np.full([2,3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [59]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [3]:
np.arange(10, 90, 3).shape

(27,)

In [4]:
np.arange(10, 90, 3).reshape(3, 3, 3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [5]:
np.arange(10, 90, 3).reshape(3, 3, -1)


array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [7]:
np.linspace(3, 27, 18)  # 3 is a domain 27 is the range but 18 is the number of elements we wanted in the array 

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])